### ISSUE TITLE
Does not install

### ISSUE THREAD

**Issue by rohitrameshrao** [icetan/sqlitepipe#1]
When I make install, i get this issue.

![image](https://user-images.githubusercontent.com/23099549/30279056-c21862dc-9729-11e7-9092-4841bf4c6bd2.png)

**Comment by icetan** [comment]
Hello Rohit,

Thank you for reporting this issue!

It should be fixed by the latest commit 7680d5cab9a6bdb342d8f6768042323add28f614.

**Comment by rohitrameshrao** [comment]
Thanks for the update!
