### ISSUE TITLE
Trouble joining on pipe'd results

### ISSUE THREAD

**Issue by cannadayr** [icetan/sqlitepipe#2]
Awesome little piece of software, but I'm having an issue getting the behavior I'm expecting.

Example follows:

```
.load sqlitepipe/sqlitepipe

select
    *
from (
    select
        '1' as a,
        '2' as b
) as tmp_tbl1

left join (
    select
        --'1' as a, -- works
        pipe('printf "%s" 1') as a, -- doesn't work
        '22' as b
) tmp_tbl2 on tmp_tbl2.a = tmp_tbl1.a;
```

Maybe I'm missing something? I used the built in 'unicode' function in sqlite to confirm the encoding was the same.

Thanks!

**Comment by cannadayr** [comment]
So a bit more info:

turns out its not joining on the result because its getting returned as a blob from sqlitepipe.

The solution seems to be to use printf to print the blob as a string before joining.

Maybe we could add this to the docs?

**Comment by icetan** [comment]
Hi! Great that you have found a use for sqlitepipe :smile:

I added some info to the readme about the return type of `pipe`.

My approach was to `CAST(pipe(...) as TEXT)` in the join and that seemed to work. Not sure about potential pitfalls with this though.

Might add an alternative function which uses `TEXT` as type instead, what do you think?

**Comment by cannadayr** [comment]
Thats a decent idea, but I don't think its unreasonable to push that responsibility to the programmer to format the output if they expect to make `join`s on it. It would also increase the amount of code (I appreciate the minimalness). But its up to you.

Another thing I might suggest, is a './configure' time flag to change the shell. I found myself reaching for bash specific features, but it was a breeze to modify & recompile.

Srsly, really neat tool.

**Comment by icetan** [comment]
Thank you for your feedback!

I'll close this issue then.

About the config, I actually started on adding a more basic function that just passes the arguments directly to `execv` so you can choose your own shell or execute a program directly.
