### ISSUE TITLE
mbtiles update fails

### ISSUE THREAD

**Issue by caleb87** [icetan/sqlitepipe#3]
I used gdal2tiles to cut tiles, then mbutil to create mbtiles. 

I'm getting an error after tying sqlitepipe to update the PNGs to JPG.

Any ideas?

```
sqlite> UPDATE images SET tile_data=pipe(tile_data, '/usr/bin/convert', '-format', 'jpg', '-quality', '80%', 'png:-', 'jpg:-');
convert: improper image header `/tmp/magick-291977fu53blog56' @ error/png.c/ReadPNGImage/3954.
convert: no images defined `jpg:-' @ error/convert.c/ConvertImageCommand/3258.
child exit code not 0: No such file or directory
Error: Executing command
```

**Comment by icetan** [comment]
Hi @caleb87,

Did you find a solution to the problem?

**Comment by caleb87** [comment]
Yes, it was too many monster energy drinks! I had mixed up a different set of mbtiles that were actually already jpg. 

Sorry to waste your time!
