### ISSUE TITLE
-bash: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by beckietech** [icetan/sqlitepipe#4]
hi, I am using MacOS high sierra, and I followed steps of install and run samples in readme, but I got the error:

SELECT pipe('Hello world!', '/usr/bin/cat');
-bash: syntax error near unexpected token `('

May I know which part is wrong? Thanks in adv.

**Comment by icetan** [comment]
Hello @beckietech!

By the look of your error message you have executed `SELECT pipe('Hello world!', '/usr/bin/cat');` in a `bash` shell.

The "SELECT"-statement is SQL syntax and should be run inside of the SQLite shell or programatically with an SQLite API.

I.e. you need to run the "SELECT" after running `sqlite3`. Here is some documentation for how the `sqlite3` command shell works <https://sqlite.org/cli.html>.

Hope this helps.
